name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y libgcc-9-dev \
                              libstdc++-9-dev \
                              libembree-dev \
                              libnetcdf-dev \
                              libhdf5-dev \
                              libeigen3-dev \
                              cmake

      - name: Update CMake
        uses: ssrobins/install-cmake@v1
        with:
          version: 3.24.3
          cache: true

          - name: GPRT Apt Dependencies
        shell: bash
        run: |
          sudo apt install -y \
          libpthread-stubs0-dev \
          libx11-xcb-dev \
          xorg-dev \
          libxinerama-dev \
          libglu1-mesa-dev \
          freeglut3-dev \
          mesa-common-dev \
          libglfw3

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true

      - name: MOAB Clone
        shell: bash
        run: |
          cd ~
          git clone https://bitbucket.org/fathomteam/moab.git
          cd moab
          git checkout 5.3.1

      - name: libMesh Clone
        shell: bash
        run: |
          cd ~
          git clone https://github.com/libMesh/libmesh.git
          cd libmesh
          git checkout v1.7.0

      - name: Environment Variables
        run: |
          echo "MOAB_SHA"=$(cd ~/moab && git rev-parse HEAD) >> $GITHUB_ENV
          echo "LIBMESH_SHA"=$(cd ~/libmesh && git rev-parse HEAD) >> $GITHUB_ENV

      - name: MOAB Cache
        id: moab-cache
        uses: actions/cache@v3
        env:
          cache-name: moab-cache
        with:
          path: ~/MOAB
          key: moab-${{ runner.os }}-${{ env.cache-name }}-${{ env.MOAB_SHA }}

      - name: libMesh Cache
        id: libmesh-cache
        uses: actions/cache@v3
        env:
          cache-name: libmesh-cache
        with:
          path: ~/LIBMESH
          key: libmesh-${{ runner.os }}-${{ env.cache-name }}-${{ env.LIBMESH_SHA }}

      - if: ${{ steps.moab-cache.outputs.cache-hit != 'true' }}
        name: Build MOAB
        run: |
          cd ~/moab
          mkdir build
          cd build
          cmake -DENABLE_HDF5=ON -DENABLE_BLASLAPACK=OFF -DCMAKE_INSTALL_PREFIX=$HOME/MOAB -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          make install

      - if: ${{ steps.libmesh-cache.outputs.cache-hit != 'true' }}
        name: Build libMesh
        shell: bash
        run: |
          cd ~
          cd libmesh
          git checkout v1.7.0
          git submodule update --init --recursive
          mkdir build
          cd build
          ../configure --prefix=$HOME/LIBMESH --enable-exodus --disable-netcdf4 --disable-eigen --disable-lapack --disable-mpi --disable-metaphysicl
          make -j4
          sudo make install

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH="$HOME/LIBMESH;$HOME/MOAB" -DCMAKE_INSTALL_PREFIX=$HOME/opt -DXDG_ENABLE_MOAB=ON -DXDG_ENABLE_LIBMESH=ON
          make -j4 install

      - name: Test
        shell: bash
        run: |
          cd build
          ctest -j4 --output-on-failure

      - name: Check installed executables
        shell: bash
        run: |
          ~/opt/bin/tools/find-volume

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
