name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Apt dependencies
       shell: bash
       run: |
         sudo apt -y update
         sudo apt install -y libgcc-9-dev libstdc++-9-dev libembree-dev libhdf5-dev cmake

      - name: Build MOAB
        shell: bash
        run: |
          cd ~
          git clone https://bitbucket.org/fathomteam/moab.git
          cd moab
          git checkout 5.3.1
          mkdir build
          cd build
          cmake -DENABLE_HDF5=ON -DENABLE_BLASLAPACK=OFF -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release
          make -j4
          sudo make install

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake ..
          make -j4

      - name: Test
        shell: bash
        run: |
          cd build
          ctest -j4 --output-on-failure
