name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y libgcc-9-dev \
                              libstdc++-9-dev \
                              libembree-dev \
                              libhdf5-dev \
                              libeigen3-dev \
                              cmake

      - name: MOAB Clone
        shell: bash
        run: |
          cd ~
          git clone https://bitbucket.org/fathomteam/moab.git
          cd moab
          git checkout 5.3.1

      - name: Environment Variables
        run: |
          echo "MOAB_SHA"=$(cd ~/moab && git rev-parse HEAD) >> $GITHUB_ENV

      - name: MOAB Cache
        id: moab-cache
        uses: actions/cache@v3
        env:
          cache-name: moab-cache
        with:
          path: ~/MOAB
          key: moab-${{ runner.os }}-${{ env.cache-name }}-${{ env.MOAB_SHA }}

      - if: ${{ steps.moab-cache.outputs.cache-hit != 'true' }}
        name: Build MOAB
        run: |
          cd ~/moab
          mkdir build
          cd build
          cmake -DENABLE_HDF5=ON -DENABLE_BLASLAPACK=OFF -DCMAKE_INSTALL_PREFIX=$HOME/MOAB -DCMAKE_BUILD_TYPE=Release ..
          make -j4
          make install

      - name: Build
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$HOME/MOAB -DCMAKE_INSTALL_PREFIX=$HOME/opt
          make -j4 install

      - name: Test
        shell: bash
        run: |
          cd build
          ctest -j4 --output-on-failure

      - name: Check installed executables
        shell: bash
        run: |
          ~/opt/bin/tools/find-volume
